name: 'move-tasks'
description: 'Github action to move tasks on Github projects'
author: 'Hung Luu <hungluu2106@gmail.com>'
inputs:
  ACTION_TOKEN:
    required: true
    description: 'Github token with required permissions on Projects & Issues'
  PROJECT_SEARCH:
    required: true
    description: 'number id or name of project to move tasks into'
  REPOSITORY:
    required: true
    description: 'owner/repo-name'
runs:
  using: 'node12'
  main: 'action/index.js'
